<?php

namespace TsAgencyLogin\Combination;

use Core\Helper\DateTime;
use TsAgencyLogin\Service\Validator\AddAgencyEmployee;
use TcFrontend\Service\Validator\ChangePassword;
use TsAgencyLogin\Service\Validator\AgencyEmployee;
use TsAgencyLogin\Service\Validator\SendPassword;
use TsAgencyLogin\Service\Validator\UpdateAgencyEmployee;
use \ElasticaAdapter\Facade\Elastica;
use \Elastica\Query;
use Smarty\Smarty;

/**
 * Class Ext_TS_Frontend_Combination_Login_Agency
 */
class Agency extends \Ext_TS_Frontend_Combination_Login_Abstract {

	/**
	 * @var \Ext_Thebing_Agency
	 */
	protected $oAgency;

	/**
	 * @var \Ext_Thebing_Agency_Contact
	 */
	protected $oAgencyContact;

	public function __construct(\Ext_TC_Frontend_Combination $oCombination, Smarty $oSmarty = null) {
		parent::__construct($oCombination, $oSmarty);
		$this->oSession = \Core\Handler\SessionHandler::getInstance();
	}

	protected function _isLoggedIn() {

		$bIsLoggedIn = parent::_isLoggedIn(); // TODO: Change the autogenerated stub

		if($bIsLoggedIn === true) {

			$this->oAgency = \Ext_Thebing_Agency::getInstance($this->_aUserData['data']['company_id']);
			$this->oAgencyContact = \Ext_Thebing_Agency_Contact::getInstance($this->_aUserData['data']['id']);

			$this->_assign('oAgency', $this->oAgency);
			$this->_assign('oAgencyContact', $this->oAgencyContact);
			
		}

		return $bIsLoggedIn;
	}

	/**
	 * Landing page
	 *
	 * @return void
	 */
	protected function _default() {
		$this->_showAgencyData();
	}

	/**
	 * Customer Id muss gesetzt werden, da dort die DB Config enthalten ist.
	 *
	 * @return int
	 */
	protected function _getCustomerDbId() {
		return 13;
	}

	/**
	 * Rückgabe der Basis-Url
	 *
	 * @return string
	 */
	protected function _getBaseUrl() {
		return '?';
	}

	/**
	 * Alle Navigations-Items setzen
	 *
	 * @return array
	 */
	protected function _getNavItems() {
		return [
			'showAgencyData',
			'showAgencyEmployeeData',
		];
	}

	/**
	 * Zeigt die "Passwort ändern" View an. Ist die selbe View die auch bei Passwort vergessen angezeigt wird.
	 * @return void
	 */
	protected function _changePassword() {

		$sActivationCode = $this->_oRequest->get('activation_key');

		/** @var \Ext_Thebing_AgencyRepository $oAgencyRepository */
		$oAgencyRepository = \Ext_Thebing_Agency::getRepository();

		$oContact = $oAgencyRepository->getContactByActivationCode($sActivationCode);

		if ($oContact === null) {
			$this->_oMessage->setMessage(\Ext_TC_Frontend_Messages::ERROR_INVALID_ACTIVATION_KEY);
			$this->_assign('sTask', 'login');
			return;
		}

		// Prüfen ob der Code abgelaufen ist
		$aDetails = $oContact->activation_codes;

		if (empty($aDetails)) {
			$this->_oMessage->setMessage(\Ext_TC_Frontend_Messages::ERROR_INVALID_ACTIVATION_KEY);
			return;
		}

		$aInfo = reset($aDetails);

		$dNow = new \DateTime();
		$dExpired = new \DateTime($aInfo['expired']);

		if ($dNow >= $dExpired) {
			$this->_oMessage->setMessage(\Ext_TC_Frontend_Messages::ERROR_INVALID_ACTIVATION_KEY);
			$this->_assign('sTask', 'login');
			return;
		}

		$this->_assign('sActivationCode', $sActivationCode);
		$this->_assign('sTask', 'changePassword');
	}

	protected function _sendPassword() {

		$sEmail = $this->_oRequest->get('user');
		$oValidator = new SendPassword();
		$oValidator->setWDValidate(new \WDValidate());
		$oValidator->setEmail($sEmail);

		if(!$oValidator->isValid()) {
			$this->_oMessage->setMessageAsArray($oValidator->getErrors());
			$this->_assign('sTask', 'requestPassword');
			return;
		}

		$oContact = \Ext_Thebing_Agency_Contact::getRepository()->findOneBy(['email'=>$sEmail]);

		//Überprüfen, ob es einen Kontakt mit der eingegebenen E-Mail-Adresse gibt, wenn ja, Aktivierungscode schicken
		if($oContact !== null) {

			$oPlaceholder = new \Ext_Thebing_Agency_Placeholder($oContact->id, 'contact');

			if(empty($this->_oCombination->items_template_id)) {
				$this->_oMessage->setMessage(\L10N::t('An error with the combination has occurred: The template could not be set!'));
				$this->_assign('sTask', 'sendPassword');
				return;
			}

			$oTemplate = \Ext_Thebing_Email_Template::getInstance(reset($this->_oCombination->items_template_id));

			if($oTemplate->getId() === 0) {
				$this->_oMessage->setMessage(\L10N::t('An error has occurred: The template could not be found!'));
				$this->_assign('sTask', 'sendPassword');
				return;
			}

			$sSubject = $oPlaceholder->replace($oTemplate->getSubject($this->_oCombination->items_language));
			$sContent = $oPlaceholder->replace($oTemplate->getContent($this->_oCombination->items_language));

			\Ext_Thebing_Mail::$oSchool = \Ext_Thebing_Client::getFirstSchool();

			//TODO ins PP auslagern
			$oMail = new \WDMail();
			$oMail->subject = $sSubject;

			if ($oTemplate->html) {
				$oMail->html = $sContent;
			} else {
				$oMail->text = $sContent;
			}

			$bSuccess = $oMail->send($sEmail);

		} else {
			//$bSuccess gibt true zurück auch wenn die E-Mail nicht existiert, aus Sicherheitsgründen
			$bSuccess = true;
		}

		if($bSuccess) {
			$this->_oMessage->setMessage(\L10N::t('If the system found a user with this e-mail address, a link with the instructions to reset your password has been sent.'), 'success');
			$this->_assign('sTask', 'sendPassword');
			$this->_showlogin();
			return;
		} else {
			$this->_oMessage->setMessage(\L10N::t('The e-mail could not be sent, please try again later!'), 'error');
			$this->_assign('sTask', 'sendPassword');
			return;
		}

	}

	/**
	 * Ändert das Passwort der Agentur
	 *
	 * @return void
	 */
	protected function _executeChangePassword() {

		$sActivationCode = $this->_oRequest->get('activation_key');

		$oContact = \Ext_Thebing_Agency::getRepository()->getContactByActivationCode($sActivationCode);

		if ($oContact !== null) {

			$oValidator = new ChangePassword();
			$sSecurityStatus = $this->_getCombinationItem('password_security');

			$oValidator->setNewPassword($this->_oRequest->get('new_password'));
			$oValidator->setNewPasswordRepeat($this->_oRequest->get('new_password_repeat'));
			$oValidator->setSecurityStatus($sSecurityStatus);

			if (!$oValidator->isValid()) {
				$this->_oMessage->setMessageAsArray($oValidator->getErrors());
				$this->_changePassword();
				return;
			}

			$sPassword = $this->_oRequest->get('new_password');

			$oCustomerDb = new \Ext_CustomerDB_DB($this->_getCustomerDbId());
			$oCustomerDb->updateCustomerField($oContact->id, 'password', $sPassword);

			// Aktivierungscode muss wieder gelöscht werden.
			$aKeys =
				[
					'agency_id' => $oContact->company_id,
					'contact_id' => $oContact->id
				];
			$aData = [];

			\DB::updateJoinData('ts_agencies_activation_codes', $aKeys, $aData);

			$this->_oMessage->setMessage('The password has been saved successfully!', 'success');
			$this->_showLogin();

		} else {

			$this->_oMessage->setMessage(\Ext_TC_Frontend_Messages::ERROR_NO_CUSTOMER);
			$this->_assign('sTask', 'login');
			return;

		}

	}

	/**
	 * Zeigt die Agenturdaten an (ist nach erfolgreichem Log-In die landing page)
	 *
	 * @return void
	 */
	public function _showAgencyData() {

		$aMessage = [];
		foreach($this->oSession->getFlashBag()->get('success', []) as $sMessage) {
			$aMessage[] = $sMessage;
		}

		$aError = [];
		foreach($this->oSession->getFlashBag()->get('error', []) as $sMessage) {
			$aError[] = $sMessage;
		}

		if(!empty($aError)) {
			$this->_setMessage(reset($aError), 'error');
		}

		if (!empty($aMessage)) {
			$this->_setMessage(reset($aMessage), 'success');
		}

		$this->_assign('oCountryFormat', new \Ext_Thebing_Gui2_Format_Country($this->_sLanguage));
		$this->_assign('oAgency', $this->oAgency);
		$this->_assign('sTask', 'agency_data');

	}

	/**
	 * Zeigt die "Agentur bearbeiten"-View an.
	 *
	 * @return void
	 */
	public function _editAgencyData() {

		$aCountries	= \Ext_Thebing_Data::getCountryList(true, false, $this->_sLanguage);
		$aCountries	= \Ext_Thebing_Util::addEmptyItem($aCountries);

		$this->_assign('aCountries', $aCountries);
		$this->_assign('oAgency', $this->oAgency);
		$this->_assign('sTask', 'update_agency');

	}

	/**
	 * Methode um geänderte Daten der Agentur zu speichern
	 *
	 * @return void
	 */
	public function _updateAgencyData() {

		$oAgency = $this->oAgency;

		$oAgency->ext_1 = $this->_oRequest->get('ext_1');
		$oAgency->ext_2 = $this->_oRequest->get('ext_2');
		$oAgency->email = $this->_oRequest->get('email');
		$oAgency->ext_10 = $this->_oRequest->get('ext_10');
		$oAgency->ext_3 = $this->_oRequest->get('ext_3');
		$oAgency->ext_4 = $this->_oRequest->get('ext_4');
		$oAgency->ext_5 = $this->_oRequest->get('ext_5');
		$oAgency->ext_6 = $this->_oRequest->get('ext_6');

		$mValidate = $oAgency->validate();

		if($mValidate === true) {

			$oAgency->save();

			$this->oSession->getFlashBag()->add('success', \L10N::t('Your changes have been saved successfully!'));
			$this->_showAgencyData();

		} else {

			$aValidate = $mValidate;

			if (
				is_array($aValidate) &&
				!empty($aValidate)
			) {

				$this->_setMessage(\L10N::t('An error has occurred, please check the marked fields!.', 'success'));

				foreach ($aValidate as $sField => $aError) {
					//löscht 'ka.' vor dem Namen des Felds, um den richtigen Namen zu übergeben
					$sField = str_replace('ka.', '', $sField);
					$sError = reset($aError);
					if(!empty($sError)) {
						$sMessage = \Ext_Gui2_Data::convertErrorKeyToMessage($sError);
						$this->oSession->getFlashBag()->add($sField, \L10N::t($sMessage));
					} else {
						$this->oSession->getFlashBag()->add($sField, \L10N::t('Please check your entries!'));
					}
				}

				$aCountries	= \Ext_Thebing_Data::getCountryList(true, false, $this->_sLanguage);
				$aCountries	= \Ext_Thebing_Util::addEmptyItem($aCountries);
				$this->_assign('aCountries', $aCountries);

				$this->_assign('oAgency', $oAgency);
				$this->_assign('sTask', 'update_agency');
				return;
			}
		}
	}

	/**
	 * Zeigt die Agenturmitarbeiter Daten an (ist nach erfolgreichem Log-In die landing page)
	 *
	 * @return void
	 */
	public function _showAgencyEmployeeData() {

		$aMessage = [];
		foreach($this->oSession->getFlashBag()->get('success', []) as $sMessage) {
			$aMessage[] = $sMessage;
		}

		$aError = [];
		foreach($this->oSession->getFlashBag()->get('error', []) as $sMessage) {
			$aError[] = $sMessage;
		}

		if(!empty($aError)) {
			$this->_setMessage(reset($aError), 'error');
		}

		if (!empty($aMessage)) {
			$this->_setMessage(reset($aMessage), 'success');
		}

		$this->_assign('oGenderFormat', new \Ext_Gui2_View_Format_Gender());
		$this->_assign('oAgency', $this->oAgency);
		$this->_assign('sTask', 'agency_employee_data');

	}

	/**
	 * Zeigt die View an um einen Mitarbeiter hinzuzufügen (edit View wird verwendet)
	 * @return void
	 */
	public function _createEmployee() {

		$this->handleEmployeeForm();
	}

	/**
	 * Zeigt die View an, in der ein Mitarbeiter bearbeitet werden kann.
	 * @return void
	 */
	public function _editEmployee() {

		$this->handleEmployeeForm((int)$this->_oRequest->get('employee'));

	}

	private function handleEmployeeForm($iEmployeeId=null) {

		$this->_assign('oAgency', $this->oAgency);

		if($iEmployeeId !== null) {

			$oContact = \Ext_Thebing_Agency_Contact::getInstance($iEmployeeId);
			// Prüfen ob die Agentur die selbe ist.
			if ((int)$oContact->company_id !== $this->oAgency->id) {
				$this->_setMessage(\L10N::t('An error has occurred: The employee could not be found!'));
				$this->_showAgencyEmployeeData();
				return;
			}

			$this->_assign('oContact', $oContact);

			$this->_assign('sTask', 'edit_employee');

		} else {
			$this->_assign('sTask', 'create_employee');
		}



	}

	/**
	 * Speichert die Daten der Mitarbeiter ab
	 * @param \Ext_Thebing_Agency_Contact $oContact
	 * @return array
	 */
	public function saveEmployee(\Ext_Thebing_Agency_Contact $oContact): array {

		$oContact->firstname = $this->_oRequest->get('firstname');
		$oContact->lastname = $this->_oRequest->get('lastname');
		$oContact->gender = $this->_oRequest->get('gender');
		$oContact->email = $this->_oRequest->get('email');
		$oContact->phone = $this->_oRequest->get('phone');
		$oContact->mobile = $this->_oRequest->get('mobile');
		$oContact->fax = $this->_oRequest->get('fax');
		$oContact->skype = $this->_oRequest->get('skype');
		$oContact->company_id = $this->oAgency->id;

		$mValidate = $oContact->validate();

		if($mValidate === true) {
			$oContact->save();
			return [];
		} else {
			return $mValidate;
		}

	}

	/**
	 * Fügt einen neuen Mitarbeiter hinzu.
	 * @return void
	 */
	public function _addEmployee() {

		$this->handleEmployeeFormSubmit();

	}

	/**
	 * POST-Methode aus der View "Mitarbeiter bearbeiten" [_editEmployee()]
	 * @return void
	 */
	public function _updateEmployee() {

		$this->handleEmployeeFormSubmit((int)$this->_oRequest->get('employee'));

	}

	private function handleEmployeeFormSubmit($iEmployeeId=null) {

		if($iEmployeeId !== null) {

			$oContact = \Ext_Thebing_Agency_Contact::getInstance($iEmployeeId);

			if ((int)$oContact->company_id !== $this->oAgency->id) {
				$this->_setMessage(\L10N::t('An error has occurred: The employee could not be found!'));
				$this->_assign('sTask', 'agency_employee_data');
			}

		} else {
			$oContact = new \Ext_Thebing_Agency_Contact();
		}

		$aValidate = $this->saveEmployee($oContact);

		if(
			is_array($aValidate) &&
			!empty($aValidate)
		) {
			$this->_setMessage(\L10N::t('An error has occurred, please check the marked fields!'));
			foreach($aValidate as $sField=>$aError) {
				$this->oSession->getFlashBag()->add($sField, \L10N::t('Please check your entries!'));
			}
			$this->_assign('aOld', $this->_oRequest->getAll());
			$this->handleEmployeeForm($iEmployeeId);
			return;
		}

		$this->oSession->getFlashBag()->add('success', \L10N::t('Your changes have been saved successfully!'));

		$this->_showAgencyEmployeeData();
	}

	/**
	 * Löscht einen Mitarbeiter
	 * @return void
	 */
	public function _deleteEmployee() {

		$oContact = \Ext_Thebing_Agency_Contact::getInstance((int)$this->_oRequest->get('employee'));

		// Prüfen ob die Agentur die selbe ist.
		if ((int)$oContact->company_id === $this->oAgency->id) {
			$oContact->delete();
			$this->oSession->getFlashBag()->add('success', \L10N::t('The employee has been deleted successfully!'));
		} else {
			$this->oSession->getFlashBag()->add('error', \L10N::t('An error has occurred: the employee could not be found!'));
		}

		$this->getRequestingUrl($this->_getBaseUrl().'task=agency_employee_data');
		header('Location: '.$this->getRequestingUrl($this->_getBaseUrl().'task=showAgencyEmployeeData'));
		die();
	}

	/**
	 * Zeigt die Übersicht der "Buchungen" an, die von der Agentur gekommen sind.
	 * @return void
	 */
	public function _inquiries() {

		$iPage = 1;
		if($this->_oRequest->hasValue('page')) {
			$iPage = (int)$this->_oRequest->get('page');
		}

		// Zeitraumfilter
		if(
			$this->_oRequest->hasValue('filter_from') &&
			$this->_oRequest->hasValue('filter_until') &&
			DateTime::isDate($this->_oRequest->input('filter_from'), 'Y-m-d') &&
			DateTime::isDate($this->_oRequest->input('filter_until'), 'Y-m-d')
		) {
			$dFrom = new DateTime($this->_oRequest->input('filter_from'));
			$dUntil = new DateTime($this->_oRequest->input('filter_until'));
		} else {
			$dUntil = new DateTime();
			$dFrom = (new DateTime())->sub(new \DateInterval('P6M'));
		}

		$aResult = $this->getInquiries($iPage, $dFrom, $dUntil);
		$aInquiries = $aResult['hits'];
		$aMonths = \Ext_TC_Util::getMonths($this->items_language);
		$aDays = \Ext_TC_Util::getDays($this->items_language);

		$oSchool = \Ext_Thebing_Client::getFirstSchool();
		$oSchoolProxy = new \Ext_Thebing_School_Proxy($oSchool);

		$oCurrencyFormat = new \Ext_Thebing_Gui2_Format_Amount();
		$oCurrencyFormat->aResultData = [
			'currency_id' => $oSchool->getCurrency(),
			'school_id' => $oSchool->id
		];

		$this->_assign('sLanguage', $this->_sLanguage);
		$this->_assign('aInquiries', $aInquiries);
		$this->_assign('aResult', $aResult);
		$this->_assign('oAgency', $this->oAgency); // TODO Auf Proxy umstellen
		$this->_assign('sTask', 'inquiries');
		$this->_assign('sDatePickerFormat',  $oSchoolProxy->getDateFormat('moment'));
		$this->_assign('sDateFormat',  $oSchoolProxy->getDateFormat());
		$this->_assign('dUntil', $dUntil->format('Y-m-d'));
		$this->_assign('dFrom', $dFrom->format('Y-m-d'));
		$this->_assign('oCurrencyFormat', $oCurrencyFormat);

	}

	/**
	 * Holt die Buchungen der Agentur
	 * @return array
	 */
	public function getInquiries($iPage = 1, \DateTime $dFrom, \DateTime $dUntil) {
		
		$iLimit = 10;
		$iStart = 0;
		if($iPage > 1) {
			$iStart = ($iPage - 1) * $iLimit;
		}

		$oSearch = new Elastica(Elastica::buildIndexName('ts_inquiry'));
		$oSearch->setFields(['customer_firstname', 'customer_lastname', 'customer_birthday_original', 'course_fulllist', 'accommodation_'.$this->_sLanguage, 'created_original', 'amount', 'amount_original', 'customer_gender_original', 'open_payment', 'open_payment_original', 'amount_open', 'amount_open_original']);
		$oSearch->setSort('created_original');
		$oSearch->setLimit($iLimit, $iStart);

		$oQuery = new \Elastica\Query\Term();
		$oQuery->setTerm('agency_id', $this->oAgency->id);

		$oSearch->addMustQuery($oQuery);

		$oQuery = new \Elastica\Query\Range('created_original', [
			'lte' => $dUntil->format('Y-m-d'),
			'gte' => $dFrom->format('Y-m-d')
		]);

		$oSearch->addMustQuery($oQuery);

		$aResult = $oSearch->search();
		$aResult['limit'] = $iLimit;
		$aResult['page'] = $iPage;

		if($aResult['total'] > 0) {
			return $aResult;
		}
	}

	/**
	 * Alle Variablen setzen, die immer vorhanden sind
	 *
	 * @return void
	 */
	public function initDefaultVars() {
		$this->_assign('sBaseURL', $this->_getBaseUrl());
		$this->_assign('oSession', $this->oSession);
	}

	/**
	 * Gibt die E-Mail Adresse zurück, die für das Anmelden benötigt wird.
	 *
	 * @param int $iLoginId
	 *
	 * @return string
	 */
	protected function getLoginEmail($iLoginId) {

		$oAgency = \Ext_Thebing_Agency::getInstance($iLoginId);

		if(empty($oAgency->email)) {
			$this->_oMessage->setMessage('A username must exist, but none has been found!');
		}

		return $oAgency->email;
	}
    
	protected function getCurrentStudents() {
		
		$sqlQuery = "
			SELECT
				`tc_c`.`firstname`,
				`tc_c`.`lastname`,
				`tc_c`.`birthday`,
				`tc_e`.`email`,
				`ts_i`.`service_from`,
				`ts_ijc`.`level_id`,
				`ts_ijc`.`courselanguage_id`,
				GROUP_CONCAT(DISTINCT IF(`tc_cd_phone`.`value`='',null,`tc_cd_phone`.`value`)) `phone`,
				`cdb2`.`ext_1` `school_name`,
				GROUP_CONCAT(DISTINCT `ktc`.`name`) `classes`,
				`ts_i`.`id` `inquiry_id`,
				`ts_ijc`.`id` `inquiry_course_id`,
				`ts_ijc`.`from`,
				`ts_ijc`.`until`
			FROM
				`kolumbus_tuition_blocks_inquiries_courses` `ktbic` JOIN
				`kolumbus_tuition_blocks` `ktb` ON
					`ktb`.`id` = `ktbic`.`block_id` AND
					`ktb`.`active` = 1 INNER JOIN
				`kolumbus_tuition_classes` `ktc` ON
					`ktc`.`id` = `ktb`.`class_id` AND
					`ktc`.`active` = 1 INNER JOIN
				`ts_inquiries_journeys_courses` `ts_ijc` ON
					`ts_ijc`.`id` = `ktbic`.`inquiry_course_id` AND
					`ts_ijc`.`active` = 1 INNER JOIN
				`ts_inquiries_journeys` `ts_ij` ON
					`ts_ij`.`id` = `ts_ijc`.`journey_id` AND
					`ts_ij`.`active` = 1 AND
					`ts_ij`.`type` & '".\Ext_TS_Inquiry_Journey::TYPE_BOOKING."' INNER JOIN
				`ts_inquiries` `ts_i` ON
					`ts_i`.`id` = `ts_ij`.`inquiry_id` AND
					`ts_i`.`active` = 1  AND
					`ts_i`.`canceled` = 0 INNER JOIN
				`ts_inquiries_to_contacts` `ts_itc` ON
					`ts_itc`.`inquiry_id` = `ts_i`.`id` AND
					`ts_itc`.`type` = 'traveller' INNER JOIN
				`tc_contacts` `tc_c` ON
					`tc_c`.`id` = `ts_itc`.`contact_id` LEFT JOIN
				`tc_contacts_numbers` `tc_cn` ON
					`tc_cn`.`contact_id` = `tc_c`.`id`  INNER JOIN
				`customer_db_2` `cdb2` ON
					`cdb2`.`id` = `ktb`.`school_id` LEFT JOIN
				`tc_contacts_to_emailaddresses` `tc_cte` ON
					`tc_cte`.`contact_id` = `tc_c`.`id` LEFT JOIN
				`tc_emailaddresses` `tc_e` ON
					`tc_cte`.`emailaddress_id` = `tc_e`.`id` LEFT JOIN
				`tc_contacts_details` `tc_cd_phone` ON
					`tc_c`.`id` = `tc_cd_phone`.`contact_id` AND
					`tc_cd_phone`.`type` IN ('phone_private', 'phone_office', 'phone_mobile') AND
					`tc_cd_phone`.`active` = 1
			WHERE
				`ts_i`.`agency_id` = :agency_id AND
				NOW() BETWEEN `ts_i`.`service_from` AND `ts_i`.`service_until`
			GROUP BY
				`ts_ijc`.`id`
			ORDER BY
				`ts_i`.`service_from`
		";
		
		$sqlParams = [
			'agency_id' => $this->oAgency->id
		];
		
		$participants = \DB::getQueryRows($sqlQuery, $sqlParams);
		
		return (array)$participants;
	}


	public function _participants() {
	
		$participants = $this->getCurrentStudents();
		
		$courseLanguages = \Ext_Thebing_Tuition_LevelGroup::getSelectOptions(null, $this->_sLanguage);
		$externalLevels = \Ext_Thebing_Tuition_Level::getList('normal', $this->_sLanguage);
		 
		$this->_assign('participants', $participants);
		$this->_assign('courseLanguages', $courseLanguages);
		$this->_assign('externalLevels', $externalLevels);

	}
	
    public function _classes() {
		
		$sqlQuery = "
			SELECT
				GROUP_CONCAT(DISTINCT CONCAT(`tc_c`.`lastname`, ', ', `tc_c`.`firstname`) ORDER BY `tc_c`.`lastname` SEPARATOR '<br>') `participants`,
				`ktcl`.`id`,
				`ktcl`.`name`,
				`ktb`.`level_id`,
				GROUP_CONCAT(
					DISTINCT CONCAT(
						`ktb`.`id`,'_',`ktbd`.`day`,'_',`ktt`.`from`,'_',`ktt`.`until`
					) 
					ORDER BY `ktb`.`id`
				) `days`,
				GROUP_CONCAT(
					DISTINCT IF(`kt`.`id` IS NOT NULL, CONCAT_WS('_', `kt`.`id`, `kt`.`firstname`, `kt`.`lastname`, `ktb`.`id`), `ktb`.`teacher_id`)
				) `teachers`,
				GROUP_CONCAT(
					DISTINCT IF(`kt_substitute`.`id` IS NOT NULL, CONCAT_WS('_', `kt_substitute`.`id`, `kt_substitute`.`firstname`, `kt_substitute`.`lastname`, `ktb`.`id`), `kt_substitute`.`id`)
				) `sub_teachers`,
				GROUP_CONCAT(IF(`ktb`.`description` ='', null, `ktb`.`description`)) `block_description`,
				GROUP_CONCAT(DISTINCT `ts_tc`.#category_name_field SEPARATOR '<br>') `categories`,
				GROUP_CONCAT(DISTINCT `kc`.`name` SEPARATOR '<br>') `rooms`
			FROM
				`kolumbus_tuition_blocks_inquiries_courses` `ktbic` JOIN
				`kolumbus_tuition_blocks` `ktb` ON
					`ktb`.`id` = `ktbic`.`block_id` AND
					`ktb`.`active` = 1 INNER JOIN
				`kolumbus_tuition_blocks_days` `ktbd` ON
					`ktb`.`id` = `ktbd`.`block_id` LEFT JOIN
				`kolumbus_tuition_blocks_to_rooms` `ktbtr` ON
					`ktb`.`id` = `ktbtr`.`block_id` LEFT JOIN
				`kolumbus_classroom` `kc` ON
					`ktbtr`.`room_id` = `kc`.`id` JOIN
				`kolumbus_tuition_classes` `ktcl` ON
					`ktcl`.`id` = `ktb`.`class_id` AND
					`ktcl`.`active` = 1 JOIN
				`kolumbus_tuition_classes_courses` `ktcc` ON
					`ktcl`.`id` = `ktcc`.`class_id` JOIN
				`kolumbus_tuition_courses` `ktc` ON
					`ktcc`.`course_id` = `ktc`.`id` JOIN
				`ts_tuition_coursecategories` `ts_tc` ON
					`ktc`.`category_id` = `ts_tc`.`id` JOIN
				`ts_inquiries_journeys_courses` `ts_ijc` ON
					`ts_ijc`.`id` = `ktbic`.`inquiry_course_id` AND
					`ts_ijc`.`active` = 1 INNER JOIN
				`ts_inquiries_journeys` `ts_ij` ON
					`ts_ij`.`id` = `ts_ijc`.`journey_id` AND
					`ts_ij`.`active` = 1 AND
					`ts_ij`.`type` & '".\Ext_TS_Inquiry_Journey::TYPE_BOOKING."' INNER JOIN
				`ts_inquiries` `ts_i` ON
					`ts_i`.`id` = `ts_ij`.`inquiry_id` AND
					`ts_i`.`active` = 1  AND
					`ts_i`.`canceled` = 0 INNER JOIN
				`ts_inquiries_to_contacts` `ts_itc` ON
					`ts_itc`.`inquiry_id` = `ts_i`.`id` AND
					`ts_itc`.`type` = 'traveller' INNER JOIN
				`tc_contacts` `tc_c` ON
					`tc_c`.`id` = `ts_itc`.`contact_id` LEFT JOIN
				`tc_contacts_numbers` `tc_cn` ON
					`tc_cn`.`contact_id` = `tc_c`.`id`  INNER JOIN
				`kolumbus_tuition_templates` `ktt` ON
					`ktt`.`id` = `ktb`.`template_id` LEFT JOIN
				`ts_teachers` `kt` ON
					`kt`.`id` = `ktb`.`teacher_id` AND
					`kt`.`active` = 1 LEFT JOIN
				`kolumbus_tuition_blocks_substitute_teachers` `ktbst` ON
					`ktbst`.`block_id` = `ktb`.`id` AND
					`ktbst`.`active` = 1 LEFT JOIN
				`ts_teachers` `kt_substitute` ON
					`kt_substitute`.`id` = `ktbst`.`teacher_id` AND
					`kt_substitute`.`active` = 1
			WHERE
				`ts_i`.`agency_id` = :agency_id AND
				NOW() BETWEEN `ts_i`.`service_from` AND `ts_i`.`service_until` AND
				`ktb`.`week` = :current_week
			GROUP BY
				`ktcl`.`id`
			ORDER BY
				`ktcl`.`name`
		";

		$sqlParams = [
			'agency_id' => $this->oAgency->id,
			'current_week' => \Carbon\Carbon::parse('this week Monday')->toDateString(),
			'category_name_field' => 'name_'.$this->_sLanguage
		];
		
		$classes = \DB::getQueryRows($sqlQuery, $sqlParams);
		
		$courseLanguages = \Ext_Thebing_Tuition_LevelGroup::getSelectOptions(null, $this->_sLanguage);
		$internalLevels = \Ext_Thebing_Tuition_Level::getList('internal', $this->_sLanguage);
		$dayFormat = new \Ext_Thebing_Gui2_Format_School_Tuition_DaysWithTime();
		$dayFormat->setLanguage($this->_sLanguage);
		$teachersFormat = new \Ext_Thebing_Gui2_Format_School_Tuition_Teachers;
				
		$this->_assign('classes', $classes);
		$this->_assign('courseLanguages', $courseLanguages);
		$this->_assign('internalLevels', $internalLevels);
		$this->_assign('dayFormat', $dayFormat);
		$this->_assign('teachersFormat', $teachersFormat);

	}
	
	public function _attendance() {
		
		$participants = $this->getCurrentStudents();
		
		$attendanceService = new \Ext_Thebing_Tuition_Attendance_Index();
		
		foreach($participants as &$participant) {

			$journeyCourse = \Ext_TS_Inquiry_Journey_Course::getInstance($participant['inquiry_course_id']);
			
			$filter['journey_course_id'] = '`ktbic`.`inquiry_course_id`';

			$sqlQuery = "
				SELECT
					(
						".\Ext_Thebing_Tuition_Attendance::getAttendanceSql('journey_course_only', $filter)."
					) `attendance_percentage`,
					(
						SELECT
							IF(
								SUM(`kta_sub`.`duration`) > 0,
								SUM(`kta_sub`.`attended`),
								NULL
							) `sum_lessons`
						FROM
							`kolumbus_tuition_attendance` `kta_sub` INNER JOIN
							`kolumbus_tuition_blocks_inquiries_courses` `ktbic_sub` ON
								`ktbic_sub`.`id` = `kta_sub`.`allocation_id` AND
								`ktbic_sub`.`active` = 1 INNER JOIN
							`kolumbus_tuition_blocks` `ktb_sub` ON
								`ktb_sub`.`id` = `ktbic_sub`.`block_id`
						WHERE
							`kta_sub`.`active` = 1 AND
							`kta_sub`.`journey_course_id` = `ktbic`.`inquiry_course_id`
					) `attendance_lessons`
				FROM
					`kolumbus_tuition_blocks_inquiries_courses` `ktbic`
				WHERE
					`ktbic`.`inquiry_course_id` = :journey_course_id AND
					`ktbic`.`active` = 1
			";
			$sqlParams = [
				'journey_course_id' => $journeyCourse->id
			];
			$attendance = \DB::getQueryRow($sqlQuery, $sqlParams);
			
			$participant = array_merge($participant, $attendance);
						
		}

		$this->_assign('attendees', $participants);
		
		$courseLanguages = \Ext_Thebing_Tuition_LevelGroup::getSelectOptions(null, $this->_sLanguage);
		 
		$this->_assign('courseLanguages', $courseLanguages);
		
	}
	
}
