<?php

return [
	'webhook_events' => [
//		'STUDENT_ENROLLMENT_CREATE', # Nur Agentur
//		'STUDENT_ENROLLMENT_UPDATE',
//		'STUDENT_ENROLLMENT_SCHOOL_ACCEPTED', # Nur Agentur
//		'STUDENT_ENROLLMENT_SCHOOL_DECLINED', # Nur Agentur
		'STUDENT_ENROLLMENT_SCHOOL_PROCESSING', # PENDING => PROCESSING
//		'STUDENT_ENROLLMENT_SCHOOL_COMMENTED',
//		'STUDENT_ENROLLMENT_SCHOOL_REVERTED_STATUS_TO_PENDING',
//		'STUDENT_ENROLLMENT_NET_INVOICE_UPLOADED',
//		'STUDENT_ENROLLMENT_GROSS_INVOICE_UPLOADED',
//		'STUDENT_ENROLLMENT_LOA_UPLOADED',
//		'STUDENT_ENROLLMENT_MISC_FILE_UPLOADED_BY_SCHOOL',
//		'STUDENT_ENROLLMENT_NET_INVOICE_DELETED',
//		'STUDENT_ENROLLMENT_GROSS_INVOICE_DELETED',
//		'STUDENT_ENROLLMENT_LOA_DELETED',
//		'STUDENT_ENROLLMENT_MISC_FILE_DELETED_BY_SCHOOL',
//		'STUDENT_ENROLLMENT_CANCELLED',
//		'STUDENT_ENROLLMENT_UNCANCELLED',
//		'STUDENT_ENROLLMENT_FORM_VALUES_CHANGED_BY_AGENCY',
//		'STUDENT_ENROLLMENT_FORM_VALUES_CHANGED_BY_SCHOOL',
//		'STUDENT_ENROLLMENT_OFFERING_ITEMS_CHANGED_BY_SCHOOL',
		'STUDENT_ENROLLMENT_SENT' # Sobald Agentur Application an Schule schickt (PENDING)
	]
];