<?php

namespace TcComplaints\Gui2\Data;

use \Ext_TC_Factory;
use \Ext_TC_Util;
use \Ext_Gui2;

abstract class Complaint extends \Ext_TC_Gui2_Data {

	/**
	 * @param \Ext_Gui2 $oGui
	 * @return \Ext_Gui2_Dialog
	 * @throws \Exception
	 */
	abstract public static function getDialog(\Ext_Gui2 $oGui);

	/**
	* @param \Ext_Gui2 $oGui
	* @return \Ext_Gui2_Dialog
	* @throws \Exception
	*/
	abstract public static function getEditDialog(\Ext_Gui2 $oGui);

	/**
	 * Gibt den Pfad der Yaml-Datei zurück
	 *
	 * @return string
	 */
	abstract public static function getComplaintYmlPath();

	/**
	 * Setzt die Bereiche der Beschwerden
	 *
	 * @param string $sLanguage
	 * @param bool $bAddEmptyItem
	 * @return array
	 */
	public static function getAreas($sLanguage = '', $bAddEmptyItem = false)  {

		$aReturn = array(
			'generally' => \Ext_TC_L10N::t('Allgemein', $sLanguage),
			'activity' => \Ext_TC_L10N::t('Aktivitäten', $sLanguage),
			'accommodation' => \Ext_TC_L10N::t('Unterkunftsanbieter', $sLanguage),
			'transfer' => \Ext_TC_L10N::t('Transferanbieter', $sLanguage),
			'teacher' => \Ext_TC_L10N::t('Lehrer', $sLanguage)
		);

		if($bAddEmptyItem) {
			$aReturn = Ext_TC_Util::addEmptyItem($aReturn, '', 'xNullx');
		}

		return $aReturn;

	}

	/**
	 * @return array|object
	 */
	public static function getUsersFilterOptions() {

		$sClassName = Ext_TC_Factory::getClassName('\TcComplaints\Gui2\Data\Complaint');
		$aOptions = Ext_TC_Factory::executeStatic($sClassName, 'getUsers');
		$aOptions = Ext_TC_Util::addEmptyItem($aOptions);

		return $aOptions;

	}

	/**
	 * @param array $aFilter
	 * @param array $aQueryParts
	 * @param array $aSql
	 */
	protected function setQueryFilterDataByRef(&$aFilter, &$aQueryParts, &$aSql) {

		if($aFilter['filter_category'] === '0') {
			$aFilter['filter_subcategory'] = '';
		}

		parent::setQueryFilterDataByRef($aFilter, $aQueryParts, $aSql); // TODO: Change the autogenerated stub
	}


}