
ALTER TABLE `customer_db_2` ADD `short` VARCHAR(50) NOT NULL AFTER `ext_1`;

ALTER TABLE `customer_db_2`
	CHANGE `id` `id` SMALLINT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	ADD `position` SMALLINT UNSIGNED NOT NULL DEFAULT '0' AFTER `user_id`;
