CREATE TABLE IF NOT EXISTS `ts_accounting_invoice_registration_log` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `created` timestamp NOT NULL,
    `changed` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `creator_id` int(11) unsigned NOT NULL DEFAULT 0,
    `editor_id` int(11) unsigned NOT NULL DEFAULT 0,
    `active` tinyint(4) DEFAULT 1,
    `document_id` int(11) unsigned NOT NULL DEFAULT 0,
    `document_number` text NOT NULL,
    `version_id` int(11) NOT NULL DEFAULT 0,
    `document_type` text NOT NULL,
    `operation` text NOT NULL,
    `body` text DEFAULT NULL,
    `response` text DEFAULT NULL,
    `success` tinyint(4) NOT NULL DEFAULT 0,
    `pdf_name` text DEFAULT NULL,
    `pdf_hash` text DEFAULT NULL,
    `verification_url` text DEFAULT NULL,
    `test` tinyint(4) NOT NULL,
    `errors` text NOT NULL,
    `rejected` tinyint(4) NOT NULL DEFAULT 0,
    `type` text NOT NULL,
    PRIMARY KEY (`id`),
    KEY `created` (`created`),
    KEY `document_id` (`document_id`),
    KEY `version_id` (`version_id`),
    KEY `success` (`success`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;