CREATE TABLE IF NOT EXISTS `tc_frontend_templates_fields` (
  `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `changed` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `active` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `creator_id` mediumint(8) unsigned NOT NULL,
  `editor_id` mediumint(8) unsigned NOT NULL,
  `template_id` mediumint(8) unsigned NOT NULL,
  `field_id` mediumint(8) unsigned NOT NULL,
  `area` varchar(10) NOT NULL COMMENT '''standard'',''checkbox'',''individual''',
  `display` varchar(8) NOT NULL COMMENT '''input'',''textarea'',''select'',''date'',''time''',
  `placeholder` varchar(255) NOT NULL,
  `label` varchar(255) NOT NULL,
  `editable` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `mandatory_field` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `mandatory_field_error` varchar(255) NOT NULL,
  `overwrite_template` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `template` text NOT NULL,
  PRIMARY KEY (`id`),
  KEY `active` (`active`),
  KEY `creator_id` (`creator_id`),
  KEY `editor_id` (`editor_id`),
  KEY `field_id` (`field_id`),
  KEY `template_id` (`template_id`),
  KEY `placeholder` (`placeholder`)
) ENGINE=InnoDB ;