<?php

namespace TcComplaints\Entity;

/**
 * Class ComplaintHistory
 * @package TcComplaints\Entity
 *
 * @property string id
 * @property string changed
 * @property string created
 * @property string active
 * @property string creator_id
 * @property string editor_id
 * @property string complaint_id
 * @property string comment
 * @property string state
 * @property string comment_type
 * @property string comment_date
 * @property string followup
 */
class ComplaintHistory extends \Ext_TC_Basic {

	// Tabellennamen
	protected $_sTable = 'tc_complaints_histories';

	// Tabellen alias
	protected $_sTableAlias = 'tc_ch';

	protected $_aFormat = array(
		'followup' => array(
			'validate' => 'DATE'
		)
	);

	/**
	 * @param string $sName
	 * @return string
	 */
	public function __get($sName) {

		if($sName === 'name') {
			$oComplaint = \Ext_TC_Factory::executeStatic('\TcComplaints\Entity\Complaint', 'getInstance', array($this->complaint_id));
			$sName = \Ext_TC_Factory::executeStatic('\TcComplaints\Gui2\Data\Complaint', 'getCommentAuthor', array($oComplaint, $this));
		} else {
			return parent::__get($sName); // TODO: Change the autogenerated stub
		}

		return $sName;
	}

	/**
	 * Gibt ein Array zurück mit allen Kommentaren einer Beschwerde
	 *
	 * @param Complaint $oComplaint
	 * @return ComplaintHistory[]
	 * @throws \Exception
	 */
	public static function getAllComplaintsCommentsViaComplaint(Complaint $oComplaint) {

		$aDataObjects = self::getRepository()->findBy(array(
			'complaint_id' => $oComplaint->getId(),
		));

		return $aDataObjects;
	}

	/**
	 * Löscht ein Kommentar einer Beschwerde
	 *
	 * @return bool
	 * @throws \Exception
	 */
	public function delete() {

		$oComplaint = Complaint::getInstance($this->complaint_id);

		$bSuccess = parent::delete();

		$aComplaintHistory = $this->getAllComplaintsCommentsViaComplaint($oComplaint);
		$oComplaintHistory = end($aComplaintHistory);

		// Da immer nur der letzte Kommentar gelöscht werden kann,
		// muss in der Complaint die latest_comment_id auf den aktuellen letzten Kommentar gesetzt werden.
		if($oComplaint->latest_comment_id !== $oComplaintHistory->id) {
			$oComplaint->latest_comment_id = $oComplaintHistory->id;
			$bSaveParents = $oComplaint->save();
		}

		if($bSaveParents && $bSuccess) {
			$bSuccess = true;
		} else {
			$bSuccess = false;
		}

		return $bSuccess;

	}
}