<?php
namespace TsAccommodation\Entity;

/**
 * @method static RequirementRepository getRepository()
 */
class Requirement extends \Ext_Thebing_Basic {

	/**
	 * @var string
	 */
	protected $_sTable = 'ts_accommodation_providers_requirements';

	/**
	 * @var string
	 */
	protected $_sTableAlias	= 'ts_apr';

	protected $_sPlaceholderClass = \TsAccommodation\Service\Placeholder\RequirementPlaceholder::class;

	/**
	 * @var array
	 */
	protected $_aFormat = array(
		'name' => array(
			'required'	=> true,
		),
	);

	protected $_aJoinTables = [
		'categories' => [
			'table' => 'ts_accommodation_categories_to_requirements',
			'foreign_key_field' => 'accommodation_category_id',
			'primary_key_field' => 'requirement_id',
			'on_delete' => 'delete'
		],
	];

	/**
	 * @return array
	 */
	public static function getSelectOptions() {

		/** @var \Ext_Thebing_Accommodation[] $aList */
		$aList = self::getRepository()->findAll();

		$aReturn = [];
		foreach($aList as $oRequirement) {
			$aReturn[$oRequirement->id] = $oRequirement->getName();
		}

		asort($aReturn);

		return $aReturn;

	}

	public function save($bLog = true) {

		parent::save($bLog); // TODO: Change the autogenerated stub

		$oStackRepository = \Core\Entity\ParallelProcessing\Stack::getRepository();
		$oStackRepository->writeToStack('ts-accommodation/requirements-status', ['requirement_id' => $this->id], 1);

		return $this;
	}

}