<?php

namespace TsActivities\Entity\Activity;

/**
 * @method static ProviderRepository getRepository()
 */
class Provider extends \Ext_Thebing_Basic {

	protected $_sTable = 'ts_activities_providers';

	protected $_sTableAlias = 'ts_actp';

	protected $_aJoinedObjects = [
		'contact' => [
			'class' => 'Ext_TS_Contact',
			'type' => 'parent',
			'check_active'=>true,
			'query' => true,
			'key' => 'contact_id'
		]
	];

	/**
	 * @return \Ext_TS_Contact
	 */
	public function getContact() {
		return $this->getJoinedObject('contact');
	}

	public function getName() {
		return $this->getContact()->address_company;
	}

	/**
	 * @param $aSqlParts
	 * @param null $sView
	 */
	public function manipulateSqlParts(&$aSqlParts, $sView = null) {

		$aSqlParts['select'] .= ", 
			`contact`.`firstname`, 
			`contact`.`lastname`,
			`tc_a`.`company`,
			`tc_e`.`email`,
			GROUP_CONCAT(DISTINCT `tc_cd_phone`.`value` SEPARATOR ', ') `phone`
		";

		$aSqlParts['from'] .= " LEFT JOIN 
			`tc_contacts_to_addresses` `tc_cta` ON
				`contact`.`id` = `tc_cta`.`contact_id` LEFT JOIN 
			`tc_addresses` `tc_a` ON
				`tc_cta`.`address_id` = `tc_a`.`id` AND
				`tc_a`.`active` = 1 LEFT JOIN 
			`tc_contacts_to_emailaddresses` `tc_cte` ON
				`contact`.`id` = `tc_cte`.`contact_id` LEFT JOIN
			`tc_emailaddresses` `tc_e` ON 
				`tc_cte`.`emailaddress_id` = `tc_e`.`id` AND 
				`tc_e`.`active` = 1 LEFT JOIN
			`tc_contacts_details` `tc_cd_phone` ON
				`contact`.`id` = `tc_cd_phone`.`contact_id` AND
				`tc_cd_phone`.`type` IN ('phone_private', 'phone_office', 'phone_mobile') AND
				`tc_cd_phone`.`active` = 1
			";

		$aSqlParts['groupby'] = '`ts_actp`.`id`';

	}

//	public function save($bLog = true) {
//
//		$this->changed = time();
//
//		return parent::save($bLog); // TODO: Change the autogenerated stub
//	}

}
