<?php

namespace TsWizard\Handler\Setup\Steps\SystemSettings;

use Tc\Service\Wizard\Structure\Form as BasicForm;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class Form extends BasicForm
{
	protected function getFieldValue(string $key, array $fieldData): mixed
	{
		if (null !== $config = $this->extractConfigKey($key)) {
			// Über Ext_TS_Config wegen json-format
			return (new \Ext_TS_Config())->{$config};
		}

		return parent::getFieldValue($key, $fieldData); // TODO: Change the autogenerated stub
	}

	protected function setFieldValue(string $key, Request $request): void
	{
		if (null !== $configKey = $this->extractConfigKey($key)) {
			// Über Ext_TS_Config wegen json-format
			$config = new \Ext_TS_Config();
			$config->{$configKey} = $request->input($key, '');
			return;
		}

		parent::setFieldValue($key, $request);
	}

	private function extractConfigKey(string $key): ?string
	{
		if (!str_starts_with($key, 'config_')) {
			return null;
		}
		return Str::after($key, 'config_');
	}

}