<?php

class Ext_TS_Inquiry_Journey_Course_Gui2_Data extends Ext_Thebing_Gui2_Data {

	public function switchAjaxRequest($_VARS)
	{
		if (
			$_VARS['task'] === 'requestAsUrl' &&
			$_VARS['action'] === 'telc_export'
		) {
			$export = new \TsTuition\Service\Export\TELCExport();

			$gui2ListData = $this->_oGui->getDataObject()->getTableQueryData(array(), array(), array(), true);

			foreach ($gui2ListData['data'] as $listRow) {

				$placeOfBirth = (array)(new \Ts\Gui2\Format\Contact\StudentlistContactDetail('place_of_birth'))->format($listRow['contact_details']);
				$countryOfBirth = (array)(new \Ts\Gui2\Format\Contact\StudentlistContactDetail('country_of_birth'))->format($listRow['contact_details']);

				$row = [
					'lastname' => $listRow['lastname'],
					'firstname' => $listRow['firstname'],
					'email' => $listRow['email'],
					'gender' => $export->mapValue('gender', $listRow['gender']),
					'mother_tongue' => $export->mapValue('mother_tongue', $listRow['mother_tongue']),
					'city' => $listRow['city'],
					'country' => $export->mapValue('country', $listRow['country_iso']),
					'place_of_birth' => \Illuminate\Support\Arr::first($placeOfBirth),
					'country_of_birth' => $export->mapValue('country_of_birth', \Illuminate\Support\Arr::first($countryOfBirth)),
				];

				if (!empty($listRow['birthday'])) {
					$birthday = \Carbon\Carbon::createFromFormat('Y-m-d', $listRow['birthday']);
					$row['birthday'] = $birthday->format('d.m.Y');
				}

				$export->row($row);
			}

			$export->output(implode('_', ['telc_export', \Carbon\Carbon::today()->format('dmY'), \System::getInterfaceLanguage()]));
			die();
		}

		return parent::switchAjaxRequest($_VARS); // TODO: Change the autogenerated stub
	}

	/**
	 * Liefert ein Array mit Kursen in Abhängigkeit der gewählten Schule
	 * @return array
	 */
	public static function getCourseList($bShort=false) {
		
		$oSchool	= Ext_Thebing_School::getSchoolFromSession();
		$iSchoolId	= (int)$oSchool->id;
		
		$oCourseList = new Ext_Thebing_Tuition_Course_List();
		$oCourseList->bForSelect= true;
		
		if($bShort === true) {
			$oCourseList->bShort = true;
		}
		
		if($iSchoolId > 0) {
			$oCourseList->iSchoolId	= $iSchoolId;
		}

		$aList = $oCourseList->getList();
		asort($aList, SORT_LOCALE_STRING);

		return $aList;
	}

	public static function getListWhere() {

		$aWhere	= array();

		$oSchool = Ext_Thebing_School::getSchoolFromSession();
		$iSchoolId = (int)$oSchool->id;
		
		if($iSchoolId > 0) {
			$aWhere['ts_ij.school_id']	= (int)$iSchoolId;
		};

		$aWhere['ts_i.canceled'] = 0;
		$aWhere['ts_ijc.visible'] = 1;

		return $aWhere;
	}

	public static function getListWhereExams() {

		$aWhere = self::getListWhere();

		$aWhere['ktc.per_unit'] = 2;

		return $aWhere;

	}

}

