<?php

class Ext_TS_System_Checks_System_Tabs_YmlChangeTabs extends Ext_TC_System_Checks_System_Tabs_AbstractMoved {

	protected function getMovedTabs(): array {

		return [
			'/admin/extensions/thebing/tuition/certificates.html' => '/gui2/page/TsTuition_certificates',
			'/admin/extensions/thebing/tuition/placementtest_results.html' => '/gui2/page/TsTuition_placementtest_results',
			'/admin/extensions/thebing/tuition/examination.html' => '/gui2/page/TsTuition_examination',
			'/admin/extensions/thebing/tuition/examination/templates.html' => '/gui2/page/Ts_examination_templates',
			'/admin/extensions/thebing/contracts.html?item=teacher' => '/gui2/page/Ts_contracts/teacher',
			'/admin/extensions/thebing/marketing/teachercategories.html' => '/gui2/page/Ts_teachercategories',
			'/admin/extensions/thebing/tuition/courses.html' => '/gui2/page/Ts_courses',
			'/admin/extensions/thebing/tuition/courses.categories.html' => '/gui2/page/Ts_courses_categories',
			'/admin/extensions/thebing/tuition/levels.html' => '/gui2/page/Ts_tuition_level',
			'/admin/extensions/thebing/tuition/levelgroups.html' => '/gui2/page/Ts_courselanguages',
			'/admin/extensions/thebing/tuition/classrooms.html' => '/gui2/page/Ts_classrooms',
			'/admin/extensions/thebing/tuition/tuitiontemplates.html' => '/gui2/page/Ts_tuitiontemplates',
			'/admin/extensions/thebing/tuition/own_overview.html' => '/gui2/page/Ts_tuition_overview',
			'/admin/extensions/thebing/tuition/colors.html' => '/gui2/page/Ts_tuition_colors',
			'/admin/extensions/thebing/accommodation/communication.html' => '/gui2/page/Ts_accommodation_communication',
			'/admin/extensions/thebing/contracts.html?item=accommodation' => '/gui2/page/Ts_contracts/accommodation',
			'/admin/extensions/thebing/accommodation/categories.html' => '/gui2/page/Ts_accommodation_categories',
			'/admin/extensions/thebing/accommodation/roomtypes.html' => '/gui2/page/Ts_accommodation_roomtypes',
			'/admin/extensions/thebing/accommodation/meals.html' => '/gui2/page/Ts_accommodation_meals',
			'/admin/extensions/thebing/marketing/accommodationcategories.html' => '/gui2/page/Ts_accommodation_costcategories',
			'/admin/extensions/thebing/marketing/transfer_package.html' => '/gui2/page/Ts_transfer_package',
			'/admin/extensions/thebing/insurances/customer.html' => '/gui2/page/Ts_insurances_customer',
			'/admin/extensions/thebing/insurances/provider.html' => '/gui2/page/Ts_insurance_provider',
			'/admin/extensions/thebing/insurances/insurances.html' => '/gui2/page/Ts_insurance',
			'/admin/extensions/thebing/insurances/weeks.html' => '/gui2/page/Ts_insurance_week',
			'/admin/extensions/thebing/accounting/incoming_inquiry_payments.html' => '/gui2/page/Ts_incoming_inquiry_payments',
			'/admin/extensions/ts/accounting/inquiry_payment_details.html' => '/gui2/page/Ts_inquiry_payment_details',
			'/admin/extensions/ts/accounting/invoice_receivables.html' => '/gui2/page/Ts_invoice_receivables',
			'/admin/extensions/thebing/accounting/provision.html' => '/gui2/page/TsAccounting_provision',
			'/admin/extensions/thebing/accounting/manual_creditnotes.html' => '/gui2/page/TsAccounting_manual_creditnotes/main',
			'/admin/extensions/thebing/accounting/erroraccountings.html' => '/gui2/page/Ts_accounting_erroraccountings',
			'/admin/extensions/thebing/accounting/cheque.html' => '/gui2/page/Ts_accounting_cheque',
			'/admin/extensions/thebing/accounting/teacher.html' => '/gui2/page/TsAccounting_teacher_payments',
			'/admin/extensions/thebing/accounting/pickup.html' => '/gui2/page/Ts_accounting_pickup',
			'/admin/extensions/thebing/admin/payments.html' => '/gui2/page/Ts_payment_methods',
			'/admin/extensions/thebing/admin/agencycategorie.html' => '/gui2/page/Ts_agencycategory',
			'/admin/extensions/thebing/marketing/agenciesgroups.html' => '/gui2/page/Ts_agenciesgroups',
			'/admin/extensions/thebing/marketing/provisions.html' => '/gui2/page/Ts_marketing_provisions',
			'/admin/extensions/thebing/marketing/agency_list.html' => '/gui2/page/Ts_marketing_agency_list',
			'/admin/extensions/thebing/marketing/special.html' => '/gui2/page/Ts_marketing_special',
			'/admin/extensions/tc/referrers.html' => '/gui2/page/Tc_referrers/school',
			'/admin/extensions/thebing/marketing/student_status_list.html' => '/gui2/page/Ts_marketing_student_status_list',
			'/admin/extensions/thebing/marketing/subject.html' => '/gui2/page/Ts_marketing_subject',
			'/admin/extensions/thebing/marketing/activity.html' => '/gui2/page/Ts_marketing_activity',
			'/admin/extensions/thebing/admin/reasons.html' => '/gui2/page/Ts_reasons',
			'/admin/extensions/thebing/marketing/saisons.html' => '/gui2/page/Ts_seasons',
			'/admin/extensions/thebing/marketing/public_holidays.html' => '/gui2/page/Ts_public_holidays',
			'/admin/extensions/thebing/marketing/additionalcosts.html' => '/gui2/page/Ts_marketing_additionalcosts',
			'/admin/extensions/thebing/marketing/teaching_units.html' => '/gui2/page/Ts_marketing_course_units',
			'/admin/extensions/thebing/marketing/cost_weeks.html' => '/gui2/page/Ts_marketing_cost_weeks',
			'/admin/extensions/thebing/marketing/weeks.html' => '/gui2/page/Ts_marketing_weeks',
			'/admin/extensions/thebing/management/pages.html' => '/gui2/page/Ts_pages',
			'/admin/extensions/thebing/management/statistics.html' => '/gui2/page/Ts_statistics',
			'/admin/extensions/thebing/admin/group.html' => '/gui2/page/Ts_usergroups',
			'/admin/extensions/thebing/admin/upload.html' => '/gui2/page/Ts_upload',
			'/admin/extensions/thebing/admin/pdf_templates.html' => '/gui2/page/Ts_pdf_templates',
			'/admin/extensions/thebing/admin/email_layouts.html' => '/gui2/page/Ts_email_layouts',
			'/admin/extensions/tc/admin/template/email/layout.html' => '/gui2/page/Tc_email_layouts2',
			'/admin/extensions/thebing/admin/email_templates.html' => '/gui2/page/Ts_email_templates',
			'/admin/extensions/tc/admin/template/automatic.html' => '/gui2/page/Tc_email_automatic',
			'/admin/extensions/thebing/admin/contract_templates.html' => '/gui2/page/Ts_contract_templates',
			'/admin/extensions/thebing/admin/schools.html' => '/gui2/page/Ts_admin_schools',
			'/admin/extensions/thebing/admin/inbox.html' => '/gui2/page/Ts_inbox',
			'/admin/extensions/tc/admin/numberranges.html' => '/gui2/page/Tc_numberranges',
			'/admin/extensions/thebing/admin/absence_categories.html' => '/gui2/page/Ts_absence_categories',
			'/admin/extensions/thebing/admin/visumstatus.html' => '/gui2/page/Ts_visumstatus',
			'/admin/extensions/tc/admin/fonts.html' => '/gui2/page/Tc_fonts',
			'/admin/extensions/thebing/marketing/positionorder.html' => '/gui2/page/Ts_positionorder',
			'/admin/extensions/tc/admin/communication/category.html' => '/gui2/page/Tc_communication_category',
			'/admin/extensions/thebing/admin/frontend_forms.html' => '/gui2/page/Ts_frontend_forms',
			'/admin/extensions/tc/admin/frontend_templates.html' => '/gui2/page/Tc_frontend_templates',
			'/admin/extensions/tc/admin/frontend_combinations.html' => '/gui2/page/Tc_frontend_combinations',
			'/admin/extensions/thebing/admin/customerupload.html' => '/gui2/page/Ts_customerupload'
		];
	}
}
